name: Docker CI Pipeline

on:
  workflow_dispatch:   # No push trigger

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Detect Code Changes
    - name: Detect changed files
      id: changes
      run: |
        git fetch --prune
        CHANGED=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
        echo "files=$CHANGED" >> $GITHUB_OUTPUT
        echo "Changed files: $CHANGED"

    # Sonar Scan ONLY if source code changed
    - name: SonarCloud Scan
      if: contains(steps.changes.outputs.files, 'src/')
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONAR_ORG }}
          -Dsonar.sources=.

    # DockerHub Login ONLY if Dockerfile changed
    - name: Login to DockerHub
      if: contains(steps.changes.outputs.files, 'Dockerfile') || contains(steps.changes.outputs.files, 'src/')
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker Image ONLY if code changed
    - name: Build Docker Image
      if: contains(steps.changes.outputs.files, 'Dockerfile') || contains(steps.changes.outputs.files, 'src/')
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/triggering:${{ github.sha }} .

    # Scan Docker Image
    - name: Scan Docker Image
      if: contains(steps.changes.outputs.files, 'Dockerfile') || contains(steps.changes.outputs.files, 'src/')
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/triggering:${{ github.sha }}
        format: table
        exit-code: '0'

    # Push Docker Image
    - name: Push Docker Image to Docker Hub
      if: contains(steps.changes.outputs.files, 'Dockerfile') || contains(steps.changes.outputs.files, 'src/')
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/triggering:${{ github.sha }}


      
          
